services:
  server:
    build: .
    restart: unless-stopped
    command:
      - "--pyx.server.port=8080"
    volumes:
      - /share/CACHEDEV1_DATA/docker/pyx/pyx.properties:/opt/pyx.properties:ro
      - /share/CACHEDEV1_DATA/docker/pyx/log4j.properties:/opt/log4j.properties:ro
      - /share/CACHEDEV1_DATA/docker/pyx/hibernate.cfg.xml:/opt/hibernate.cfg.xml:ro
      - /share/CACHEDEV1_DATA/docker/pyx/pyx.sqlite:/opt/pyx.sqlite:ro
    ports:
      - 9321:8080
    networks:
      - porty_default
    environment:
      - TOMCAT_USER=tomcat_user
      - TOMCAT_PASSWORD=tomcat_password
      - DB_NAME=pyx
      - DB_USER=pyx
      - DB_PASSWORD=CorrectHorseBatteryStaple

networks:
  porty_default:
    name: porty_default
    external: true
